#快手视频刷金币测试，抓包获取secrets
 name:快手视频浏览

 on:
 workflow dispatch: schedule:
 cron:'*/150-14*
 watch:
 types:started
 jobs:
 build:
 runs-on:ubuntu-latest
 if: github.event.repository.owner.id == qithubeventsender.id
 env:
 KUAISHOUMV:${l secrets.KUAISHOUMV TZ:Asia/shanghai
 steps:
 - name:Checkout
 run:
 git clone
 https://github.com/Sunert/Scripts.git~/Scripts
 name: Use Node.js 12.x
 uses: actions/setup-node@v1
 with:
 node-version:12.x
- name: npm install
 run:
 cd -/Scripts
 npm install
 - name:'运行 【快手视频】
 if:env.KUAISHOUMV
 run:
 cd ~/Scripts
 node Task/Auto Kuaishou.js
 env:
 PUSH KEY:$l secrets.PUSH_KEY ))
 TG_B0T_TOKEN:${l secrets.TG_B0T_TOKEN TG_USER_ID: secretsTG_USER_ID)
